### ISSUE TITLE
Crash with latest mockito2

### ISSUE THREAD

**Issue by TWiStErRob** [jayway/powermock#686]
**What steps will reproduce the problem?**
```java
@Mock Blah mock;
@Before public void setUp() {
	MockitoAnnotations.initMocks(this);
}
@Test public void test() {
	when(mock.methodCall()).thenReturn(42);
}
```
**What is the expected output?**
a running test, passing or failing

**What do you see instead?**
```
java.lang.NoSuchMethodError: org.mockito.internal.invocation.InvocationImpl.<init>(Ljava/lang/Object;Lorg/mockito/internal/invocation/MockitoMethod;[Ljava/lang/Object;ILorg/mockito/internal/invocation/realmethod/RealMethod;)V
	at org.powermock.api.mockito.repackaged.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:58)
	at net.twisterrob.Blah$$EnhancerByMockitoWithCGLIB$$38de944b.getJubileeBackground(<generated>)
```

**What version of the product are you using?**
```
+--- org.mockito:mockito-core:2.0.93-beta
+--- org.powermock:powermock-api-mockito2:1.6.5
|    +--- org.mockito:mockito-core:2.0.42-beta -> 2.0.93-beta (*)
```

**On what operating system?**
Windows 10 x64

**Please provide any additional information below.**
There was a breaking change in `mockito:2.0.48-beta`: https://github.com/mockito/mockito/commit/3f207146f807bfe472fd99d2e9a139d42763a453
which means that this instantiation is no longer valid: [MethodInterceptorFilter.java](https://github.com/jayway/powermock/blob/e386adc01057305d826ed7c271eefd9a0b5d39fc/api/mockito2/src/main/java/org/powermock/api/mockito/repackaged/MethodInterceptorFilter.java#L58)

The latest version `powermock-api-mockito2` works with is `mockito:2.0.47-beta`, which is far down in the [changes list](https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md#2047-beta-2016-04-16-1810-utc)

**Comment by thekingnothing** [comment]
It's the same issue as the #681. Mockito 2 is in beta state and is very quickly changed and PowerMock cannot support right now all those changes.

**Comment by TWiStErRob** [comment]
Hmm, sorry about that. I explicitly remember searching for the class name in the exception in the issues here, but there were no results. I guess I should've tried "mockito2". Can you please change the version number at https://github.com/jayway/powermock/wiki/MockitoUsage from 2.0+ to "2.0.0-beta - 2.0.42-beta"?

**Comment by TWiStErRob** [comment]
Can we revisit this one? https://github.com/mockito/mockito/issues/123#issuecomment-251104632
